# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{commons-io}
  s.version = "1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Cooper - martinc@apache.org", "Matthew Hawthorne - matth@apache.org", "dIon Gillard - dion@apache.org", "Jukka Zitting - ", "Jeremias Maerki - jeremias@apache.org", "Stephen Colebourne - ", "Scott Sanders - sanders@apache.org", "Henri Yandell - bayard@apache.org", "Nicola Ken Barozzi - nicolaken@apache.org", "Niall Pemberton - ", "Jochen Wiedmann - jochen.wiedmann@gmail.com", "Rob Oxspring - roxspring@apache.org"]
  s.date = %q{2009-11-22}
  s.description = %q{Commons-IO contains utility classes, stream implementations, file filters, file comparators and endian classes.}
  s.email = %q{autobuild@javagems.org}
  s.homepage = %q{http://www.javagems.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A JavaGem version of Commons IO - packaged by JavaGems (http://www.javagems.org) - original by The Apache Software Foundation (http://www.apache.org/)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<junit>, ["~> 3.8.1"])
    else
      s.add_dependency(%q<junit>, ["~> 3.8.1"])
    end
  else
    s.add_dependency(%q<junit>, ["~> 3.8.1"])
  end
end

